import React, { useCallback, useEffect, useMemo, useState } from "react";
import { authenticatedRestFetchWithRefresh } from "../../lib/serviceosAuthClient.js";
import { StatusBadge, TechnicalDetails } from "../../components/ui.jsx";
import { SERVICEOS_FINANCIAL_INVALIDATED_EVENT, invalidateServiceOSFinancials } from "../../lib/serviceosFinancialPerformance.js";

async function rpc(name, body) {
  const response = await authenticatedRestFetchWithRefresh(`rpc/${name}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) });
  const text = await response?.text().catch(() => ""); let data = null;
  try { data = text ? JSON.parse(text) : null; } catch { data = null; }
  if (!response?.ok) throw new Error(data?.message || data?.error || `${name} failed.`);
  return Array.isArray(data) ? data[0] : data;
}

function money(value, currency) { return new Intl.NumberFormat("en", { style: "currency", currency }).format(Number(value || 0)); }
function mondayIso() { const d = new Date(); const day = d.getDay() || 7; d.setDate(d.getDate() - day + 1); return d.toISOString().slice(0, 10); }
function displayMethod(value) { return String(value || "").replaceAll("_", " ").replace(/\b\w/g, letter => letter.toUpperCase()); }

export default function CleanerPayablesPanel({ revenueContext }) {
  const [data,setData]=useState(null),[workers,setWorkers]=useState([]),[error,setError]=useState(""),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false);
  const [workerId,setWorkerId]=useState("all"),[rateWorkerId,setRateWorkerId]=useState(""),[rate,setRate]=useState(""),[weekStart,setWeekStart]=useState(mondayIso),[weeklyHours,setWeeklyHours]=useState("40");
  const [bucket,setBucket]=useState("outstanding"),[selected,setSelected]=useState([]),[paymentMethod,setPaymentMethod]=useState("ach"),[paymentReference,setPaymentReference]=useState("");
  const orgId=revenueContext?.orgId,businessUnitId=revenueContext?.primaryBusinessUnitId,role=revenueContext?.roleCode;
  const load=useCallback(async()=>{if(!orgId||!businessUnitId)return;setBusy(true);setError("");try{
    const [dashboard,workerResponse]=await Promise.all([rpc("get_cleaner_payables_dashboard",{p_organization_id:orgId,p_business_unit_id:businessUnitId,p_limit:1000}),authenticatedRestFetchWithRefresh(`worker?select=id,display_name,email&business_unit_id=eq.${encodeURIComponent(businessUnitId)}&status=eq.active&order=display_name.asc`)]);
    if(!workerResponse?.ok)throw new Error("Active cleaners could not be loaded."); const workerRows=await workerResponse.json();
    setData(dashboard);setWorkers(Array.isArray(workerRows)?workerRows:[]);setRateWorkerId(current=>current||workerRows?.[0]?.id||"");
  }catch(e){setError(e?.message||String(e));}finally{setBusy(false);}},[orgId,businessUnitId]);
  useEffect(()=>{load();},[load]);
  useEffect(()=>{const refreshPayables=(event)=>{if(!event?.detail?.businessUnitId||event.detail.businessUnitId===businessUnitId)load();};window.addEventListener(SERVICEOS_FINANCIAL_INVALIDATED_EVENT,refreshPayables);return()=>window.removeEventListener(SERVICEOS_FINANCIAL_INVALIDATED_EVENT,refreshPayables);},[businessUnitId,load]);

  const rows=Array.isArray(data?.rows)?data.rows:[],currency=data?.scope?.currency_code||"USD";
  const visibleRows=useMemo(()=>rows.filter(row=>(workerId==="all"||row.worker_id===workerId)&&(bucket==="paid"?row.status==="paid":["pending","approved"].includes(row.status))),[rows,workerId,bucket]);
  const selectedRows=visibleRows.filter(row=>selected.includes(row.id));
  const selectedPending=selectedRows.filter(row=>row.status==="pending"),selectedApproved=selectedRows.filter(row=>row.status==="approved");
  const selectedTotal=selectedRows.reduce((total,row)=>total+Number(row.amount||0),0);
  const csv=useMemo(()=>["Cleaner,Work Order,Actual Hours,Hourly Rate,Amount,Currency,Status,Approved,Paid,Payment Method,Payment Reference",...visibleRows.map(r=>[r.worker_name,r.work_order_number,r.actual_hours,r.hourly_rate,r.amount,r.currency_code,r.status,r.approved_at,r.paid_at,r.payment_method,r.payment_reference].map(v=>`"${String(v??"").replaceAll('"','""')}"`).join(","))].join("\n"),[visibleRows]);
  function exportCsv(){const url=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"}));const a=document.createElement("a");a.href=url;a.download=`cleaner-payables-${data?.scope?.market_code||"market"}-${bucket}.csv`;a.click();URL.revokeObjectURL(url);}
  function toggle(id){setSelected(current=>current.includes(id)?current.filter(item=>item!==id):[...current,id]);}
  async function transition(name,body,success){setBusy(true);setError("");setNotice("");try{const result=await rpc(name,body);setNotice(`${success}: ${money(result?.amount,currency)} across ${result?.count||0} payout${result?.count===1?"":"s"}.`);setSelected([]);setPaymentReference("");await load();invalidateServiceOSFinancials({businessUnitId,reason:"contractor_payable_settlement"});}catch(e){setError(e?.message||String(e));}finally{setBusy(false);}}
  function approveSelected(){return transition("staff_approve_contractor_payables",{p_organization_id:orgId,p_business_unit_id:businessUnitId,p_payable_ids:selectedPending.map(row=>row.id),p_note:"Approved in Cleaner Payables workspace"},"Payroll approved");}
  function recordPaid(){if(!paymentReference.trim())return setError("Enter the transfer confirmation or payment reference before recording payment.");return transition("staff_mark_contractor_payables_paid",{p_organization_id:orgId,p_business_unit_id:businessUnitId,p_payable_ids:selectedApproved.map(row=>row.id),p_payment_method:paymentMethod,p_payment_reference:paymentReference.trim(),p_note:"Payment recorded in Cleaner Payables workspace"},"Payment recorded");}
  async function saveRate(){setBusy(true);setError("");try{await rpc("staff_set_worker_hourly_compensation",{p_worker_id:rateWorkerId,p_hourly_rate:Number(rate),p_effective_from:new Date().toISOString()});setRate("");await load();}catch(e){setError(e?.message||String(e));}finally{setBusy(false);}}
  async function saveCapacity(){setBusy(true);setError("");try{await rpc("staff_set_worker_weekly_capacity",{p_worker_id:rateWorkerId,p_week_start:weekStart,p_available_hours:Number(weeklyHours)});await load();}catch(e){setError(e?.message||String(e));}finally{setBusy(false);}}

  return <section id="cleaner-payables" className="financial-performance-panel cleaner-payables-panel" aria-labelledby="cleaner-payables-title"><header><div><p className="admin-eyebrow">Payroll readiness · {data?.scope?.market_code||"Active market"}</p><h2 id="cleaner-payables-title">Cleaner Payables</h2><p>Approve earned compensation, record external payment evidence, and retain each team member’s payout history.</p></div><button className="huc-button huc-button--secondary" onClick={load} disabled={busy}>Refresh</button></header>
    {error?<div className="financial-alert" role="alert">{error}</div>:null}{notice?<div className="financial-alert financial-alert--success" role="status">{notice}</div>:null}
    <div className="financial-kpi-grid"><article className="financial-kpi-card"><span>Pending approval</span><strong>{money(data?.pending_total,currency)}</strong><small>Earned and currently unpaid</small></article><article className="financial-kpi-card"><span>Approved to pay</span><strong>{money(data?.approved_total,currency)}</strong><small>Authorized but not yet recorded paid</small></article><article className="financial-kpi-card"><span>Paid historically</span><strong>{money(data?.paid_total,currency)}</strong><small>Settled with payment evidence</small></article></div>
    <div className="admin-filter-bar"><label className="admin-select-field"><span>Team member</span><select value={workerId} onChange={e=>{setWorkerId(e.target.value);setSelected([]);}}><option value="all">All team members</option>{workers.map(w=><option key={w.id} value={w.id}>{w.display_name||w.email}</option>)}</select></label><div className="payables-bucket-tabs" role="tablist" aria-label="Payout status"><button role="tab" aria-selected={bucket==="outstanding"} className={bucket==="outstanding"?"active":""} onClick={()=>{setBucket("outstanding");setSelected([]);}}>Outstanding</button><button role="tab" aria-selected={bucket==="paid"} className={bucket==="paid"?"active":""} onClick={()=>{setBucket("paid");setSelected([]);}}>Paid History</button></div><button aria-label="Export payroll CSV" className="huc-button huc-button--secondary" disabled={!visibleRows.length} onClick={exportCsv}>Export {bucket==="paid"?"history":"payroll"} CSV</button></div>
    {role==="owner_admin"&&bucket==="outstanding"?<div className="payables-action-bar"><strong>{selectedRows.length} selected · {money(selectedTotal,currency)}</strong><button className="huc-button huc-button--secondary" disabled={busy||!selectedPending.length||selectedApproved.length>0} onClick={approveSelected}>Approve selected</button><label><span>Payment method</span><select value={paymentMethod} onChange={e=>setPaymentMethod(e.target.value)}><option value="ach">ACH</option><option value="zelle">Zelle</option><option value="etransfer">E-transfer</option><option value="check">Check</option><option value="cash">Cash</option><option value="payroll_provider">Payroll provider</option><option value="other">Other</option></select></label><label><span>Confirmation / reference</span><input value={paymentReference} onChange={e=>setPaymentReference(e.target.value)} placeholder="Required after money is sent" /></label><button className="huc-button" disabled={busy||!selectedApproved.length||selectedPending.length>0||!paymentReference.trim()} onClick={recordPaid}>Record payment sent</button><small>ServiceOS records the settlement; send funds through your bank or payroll provider first.</small></div>:null}
    {visibleRows.length?<div className="financial-table payables-table" role="table" aria-label={bucket==="paid"?"Paid cleaner history":"Outstanding cleaner payables"}><div className="financial-table__row financial-table__head" role="row"><span>Select</span><span>Cleaner</span><span>Hours</span><span>Amount</span><span>Status</span><span>{bucket==="paid"?"Payment evidence":"Work order"}</span></div>{visibleRows.map(row=><div className="financial-table__row" role="row" key={row.id}><span>{bucket==="outstanding"&&role==="owner_admin"?<input aria-label={`Select ${row.worker_name} ${row.work_order_number}`} type="checkbox" checked={selected.includes(row.id)} onChange={()=>toggle(row.id)}/>:"—"}</span><span><b>{row.worker_name}</b></span><span>{row.compensation_method==="hourly"?Number(row.actual_hours).toFixed(2):"Flat"}</span><span>{money(row.amount,row.currency_code)}</span><span><StatusBadge tone={row.status==="pending"?"warning":"success"}>{row.status}</StatusBadge></span><span>{bucket==="paid"?<><b>{displayMethod(row.payment_method)}</b><small>{row.paid_at?new Date(row.paid_at).toLocaleDateString():"Paid"} · {row.payment_reference||"Legacy record"}</small></>:<>{row.work_order_number||"Work order"}<TechnicalDetails><span>Payable: {row.id}</span></TechnicalDetails></>}</span></div>)}</div>:<div className="financial-empty-state"><StatusBadge tone="neutral">No governed data</StatusBadge><h3>{bucket==="paid"?"No paid history for this team member":"No outstanding cleaner payables"}</h3><p>{bucket==="paid"?"Recorded payments will remain available here for reconciliation.":"Outstanding payables appear after QA approval."}</p></div>}
    <details className="payables-setup"><summary>Compensation rate and capacity setup</summary><div className="admin-filter-bar"><label className="admin-select-field"><span>Cleaner</span><select value={rateWorkerId} onChange={e=>setRateWorkerId(e.target.value)}>{workers.map(w=><option key={w.id} value={w.id}>{w.display_name||w.email}</option>)}</select></label>{role==="owner_admin"?<><label className="admin-search-field"><span>Hourly rate ({currency})</span><input type="number" min="0.01" max="500" step="0.01" value={rate} onChange={e=>setRate(e.target.value)}/></label><button className="huc-button huc-button--secondary" disabled={busy||!rateWorkerId||!rate} onClick={saveRate}>Set governed rate</button></>:null}<label className="admin-search-field"><span>Week starting Monday</span><input type="date" value={weekStart} onChange={e=>setWeekStart(e.target.value)}/></label><label className="admin-search-field"><span>Available hours</span><input type="number" min="0" max="120" step="0.5" value={weeklyHours} onChange={e=>setWeeklyHours(e.target.value)}/></label><button className="huc-button huc-button--secondary" disabled={busy||!rateWorkerId} onClick={saveCapacity}>Save capacity</button></div></details>
  </section>;
}
