import React, { useCallback, useEffect, useState } from "react";
import { StatusBadge } from "../../components/ui.jsx";
import { activateApplicant, fetchActiveContractors, fetchApplicantInspector, fetchApplicantPipeline, setContractorDispatchReadiness } from "../../lib/serviceosTeamHiring.js";
import ActiveContractorDirectory from "./ActiveContractorDirectory.jsx";
import ApplicantPipelineBoard from "./ApplicantPipelineBoard.jsx";
import ApplicantReviewModal from "./ApplicantReviewModal.jsx";

export default function TeamHiringWorkspace({ revenueContext }) {
  const businessUnitId = revenueContext?.primaryBusinessUnitId; const marketCode = revenueContext?.activeBusinessUnitCode || "HUC";
  const [applicants, setApplicants] = useState([]); const [contractors, setContractors] = useState([]); const [selected, setSelected] = useState(null); const [inspector, setInspector] = useState(null);
  const [loading, setLoading] = useState(true); const [busyId, setBusyId] = useState(""); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  const load = useCallback(async () => { if (!businessUnitId) return; setLoading(true); setError(""); try { const [nextApplicants, nextContractors] = await Promise.all([fetchApplicantPipeline(businessUnitId, marketCode), fetchActiveContractors(businessUnitId)]); setApplicants(nextApplicants); setContractors(nextContractors); } catch (nextError) { setError(nextError?.message || "Team records could not be loaded."); } finally { setLoading(false); } }, [businessUnitId, marketCode]);
  useEffect(() => { load(); }, [load]);
  const review = async (applicant) => { setSelected(applicant); setInspector(null); setError(""); try { setInspector(await fetchApplicantInspector(businessUnitId, applicant)); } catch (nextError) { setError(nextError?.message || "Applicant review could not be loaded."); } };
  const advance = async () => { if (!selected?.engagement_id) return; setBusyId(selected.id); setError(""); try { await activateApplicant(businessUnitId, selected.engagement_id); setNotice(`${selected.name} is now operable for dispatch.`); setSelected(null); await load(); } catch (nextError) { setError(nextError?.message || "Activation could not be completed."); } finally { setBusyId(""); } };
  const readiness = async (contractor, ready) => { setBusyId(contractor.id); setError(""); try { await setContractorDispatchReadiness(contractor.id, ready); setContractors((current) => current.map((item) => item.id === contractor.id ? { ...item, dispatchReady: ready, status: ready ? "active" : "inactive" } : item)); setNotice(`${contractor.display_name} ${ready ? "is eligible" : "is held"} for dispatch.`); } catch (nextError) { setError(nextError?.message || "Readiness could not be updated."); } finally { setBusyId(""); } };
  return <section className="team-hiring-workspace" aria-labelledby="team-hiring-title"><header className="workspace-heading"><div><p className="admin-eyebrow">Team & Hiring · {marketCode}</p><h2 id="team-hiring-title">Build and deploy a reliable field team</h2><p>Governed applicant progression, compliance review, compensation visibility, and dispatch controls.</p></div><div><StatusBadge tone={error ? "danger" : "success"}>{loading ? "Loading" : "Live"}</StatusBadge><button className="huc-button huc-button--secondary" onClick={load} disabled={loading}>Refresh</button></div></header>{error ? <div className="financial-alert" role="alert">{error}</div> : null}{notice ? <div className="team-notice" role="status">{notice}</div> : null}<ApplicantPipelineBoard applicants={applicants} onReview={review} /><ActiveContractorDirectory contractors={contractors} marketCode={marketCode} busyId={busyId} onReadiness={readiness} /><ApplicantReviewModal applicant={selected} inspector={inspector} busy={busyId === selected?.id} onClose={() => setSelected(null)} onAdvance={advance} /></section>;
}
