-- CONTROL-PLANE READ-ONLY SCHEMA EVIDENCE
-- Source: production-like pg_catalog metadata. No application rows copied.
-- Historical structural evidence only. Review before using in a new-environment baseline.

ALTER TABLE public.app_role ADD CONSTRAINT app_role_code_key UNIQUE (code);
ALTER TABLE public.app_role ADD CONSTRAINT app_role_pkey PRIMARY KEY (id);
ALTER TABLE public.app_user ADD CONSTRAINT app_user_auth_user_id_fkey FOREIGN KEY (auth_user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.app_user ADD CONSTRAINT app_user_auth_user_id_key UNIQUE (auth_user_id);
ALTER TABLE public.app_user ADD CONSTRAINT app_user_pkey PRIMARY KEY (id);
ALTER TABLE public.app_user ADD CONSTRAINT app_user_status_check CHECK (status = ANY (ARRAY['invited'::text, 'active'::text, 'suspended'::text, 'inactive'::text]));
ALTER TABLE public.audit_event ADD CONSTRAINT audit_event_actor_user_id_fkey FOREIGN KEY (actor_user_id) REFERENCES app_user(id);
ALTER TABLE public.audit_event ADD CONSTRAINT audit_event_business_unit_id_fkey FOREIGN KEY (business_unit_id) REFERENCES business_unit(id);
ALTER TABLE public.audit_event ADD CONSTRAINT audit_event_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organization(id);
ALTER TABLE public.audit_event ADD CONSTRAINT audit_event_pkey PRIMARY KEY (id);
ALTER TABLE public.business_unit ADD CONSTRAINT business_unit_jurisdiction_id_fkey FOREIGN KEY (jurisdiction_id) REFERENCES jurisdiction(id);
ALTER TABLE public.business_unit ADD CONSTRAINT business_unit_organization_id_code_key UNIQUE (organization_id, code);
ALTER TABLE public.business_unit ADD CONSTRAINT business_unit_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organization(id);
ALTER TABLE public.business_unit ADD CONSTRAINT business_unit_pkey PRIMARY KEY (id);
ALTER TABLE public.business_unit ADD CONSTRAINT business_unit_status_check CHECK (status = ANY (ARRAY['active'::text, 'inactive'::text, 'archived'::text]));
ALTER TABLE public.campaign ADD CONSTRAINT campaign_marketing_source_id_fkey FOREIGN KEY (marketing_source_id) REFERENCES marketing_source(id);
ALTER TABLE public.campaign ADD CONSTRAINT campaign_organization_id_code_key UNIQUE (organization_id, code);
ALTER TABLE public.campaign ADD CONSTRAINT campaign_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organization(id);
ALTER TABLE public.campaign ADD CONSTRAINT campaign_pkey PRIMARY KEY (id);
ALTER TABLE public.configuration_version ADD CONSTRAINT configuration_version_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES app_user(id);
ALTER TABLE public.configuration_version ADD CONSTRAINT configuration_version_business_unit_id_fkey FOREIGN KEY (business_unit_id) REFERENCES business_unit(id);
ALTER TABLE public.configuration_version ADD CONSTRAINT configuration_version_jurisdiction_id_fkey FOREIGN KEY (jurisdiction_id) REFERENCES jurisdiction(id);
ALTER TABLE public.configuration_version ADD CONSTRAINT configuration_version_organization_id_configuration_type_ve_key UNIQUE (organization_id, configuration_type, version);
ALTER TABLE public.configuration_version ADD CONSTRAINT configuration_version_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organization(id);
ALTER TABLE public.configuration_version ADD CONSTRAINT configuration_version_pkey PRIMARY KEY (id);
ALTER TABLE public.configuration_version ADD CONSTRAINT configuration_version_status_check CHECK (status = ANY (ARRAY['draft'::text, 'approved'::text, 'published'::text, 'retired'::text]));
ALTER TABLE public.contact ADD CONSTRAINT contact_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES customer(id) ON DELETE CASCADE;
ALTER TABLE public.contact ADD CONSTRAINT contact_pkey PRIMARY KEY (id);
ALTER TABLE public.customer ADD CONSTRAINT customer_business_unit_id_fkey FOREIGN KEY (business_unit_id) REFERENCES business_unit(id);
ALTER TABLE public.customer ADD CONSTRAINT customer_customer_type_check CHECK (customer_type = ANY (ARRAY['person'::text, 'business'::text]));
ALTER TABLE public.customer ADD CONSTRAINT customer_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organization(id);
ALTER TABLE public.customer ADD CONSTRAINT customer_pkey PRIMARY KEY (id);
ALTER TABLE public.customer ADD CONSTRAINT customer_status_check CHECK (status = ANY (ARRAY['lead'::text, 'active'::text, 'inactive'::text, 'archived'::text]));
ALTER TABLE public.external_reference ADD CONSTRAINT external_reference_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organization(id);
ALTER TABLE public.external_reference ADD CONSTRAINT external_reference_pkey PRIMARY KEY (id);
ALTER TABLE public.external_reference ADD CONSTRAINT external_reference_system_name_external_id_entity_type_key UNIQUE (system_name, external_id, entity_type);
ALTER TABLE public.idempotency_key ADD CONSTRAINT idempotency_key_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organization(id);
ALTER TABLE public.idempotency_key ADD CONSTRAINT idempotency_key_pkey PRIMARY KEY (id);
ALTER TABLE public.idempotency_key ADD CONSTRAINT idempotency_key_scope_key_key UNIQUE (scope, key);
ALTER TABLE public.jurisdiction ADD CONSTRAINT jurisdiction_code_key UNIQUE (code);
ALTER TABLE public.jurisdiction ADD CONSTRAINT jurisdiction_pkey PRIMARY KEY (id);
ALTER TABLE public.marketing_source ADD CONSTRAINT marketing_source_organization_id_code_key UNIQUE (organization_id, code);
ALTER TABLE public.marketing_source ADD CONSTRAINT marketing_source_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organization(id);
ALTER TABLE public.marketing_source ADD CONSTRAINT marketing_source_pkey PRIMARY KEY (id);
ALTER TABLE public.migration_lineage ADD CONSTRAINT migration_lineage_migration_name_source_table_source_id_tar_key UNIQUE (migration_name, source_table, source_id, target_table);
ALTER TABLE public.migration_lineage ADD CONSTRAINT migration_lineage_pkey PRIMARY KEY (id);
ALTER TABLE public.migration_lineage ADD CONSTRAINT migration_lineage_status_check CHECK (status = ANY (ARRAY['pending'::text, 'migrated'::text, 'skipped'::text, 'error'::text, 'reconciled'::text]));
ALTER TABLE public.organization ADD CONSTRAINT organization_code_key UNIQUE (code);
ALTER TABLE public.organization ADD CONSTRAINT organization_pkey PRIMARY KEY (id);
ALTER TABLE public.organization ADD CONSTRAINT organization_status_check CHECK (status = ANY (ARRAY['active'::text, 'inactive'::text, 'archived'::text]));
ALTER TABLE public.service_location ADD CONSTRAINT service_location_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES customer(id) ON DELETE CASCADE;
ALTER TABLE public.service_location ADD CONSTRAINT service_location_jurisdiction_id_fkey FOREIGN KEY (jurisdiction_id) REFERENCES jurisdiction(id);
ALTER TABLE public.service_location ADD CONSTRAINT service_location_pkey PRIMARY KEY (id);
ALTER TABLE public.user_membership ADD CONSTRAINT user_membership_app_user_id_fkey FOREIGN KEY (app_user_id) REFERENCES app_user(id) ON DELETE CASCADE;
ALTER TABLE public.user_membership ADD CONSTRAINT user_membership_app_user_id_organization_id_business_unit_i_key UNIQUE (app_user_id, organization_id, business_unit_id, role_id);
ALTER TABLE public.user_membership ADD CONSTRAINT user_membership_business_unit_id_fkey FOREIGN KEY (business_unit_id) REFERENCES business_unit(id) ON DELETE CASCADE;
ALTER TABLE public.user_membership ADD CONSTRAINT user_membership_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organization(id) ON DELETE CASCADE;
ALTER TABLE public.user_membership ADD CONSTRAINT user_membership_pkey PRIMARY KEY (id);
ALTER TABLE public.user_membership ADD CONSTRAINT user_membership_role_id_fkey FOREIGN KEY (role_id) REFERENCES app_role(id);
ALTER TABLE public.user_membership ADD CONSTRAINT user_membership_status_check CHECK (status = ANY (ARRAY['active'::text, 'inactive'::text]));
ALTER TABLE public.worker ADD CONSTRAINT worker_app_user_id_fkey FOREIGN KEY (app_user_id) REFERENCES app_user(id);
ALTER TABLE public.worker ADD CONSTRAINT worker_business_unit_id_fkey FOREIGN KEY (business_unit_id) REFERENCES business_unit(id);
ALTER TABLE public.worker ADD CONSTRAINT worker_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organization(id);
ALTER TABLE public.worker ADD CONSTRAINT worker_pkey PRIMARY KEY (id);
ALTER TABLE public.worker ADD CONSTRAINT worker_status_check CHECK (status = ANY (ARRAY['applicant'::text, 'onboarding'::text, 'active'::text, 'suspended'::text, 'inactive'::text, 'archived'::text]));
ALTER TABLE public.worker ADD CONSTRAINT worker_worker_type_check CHECK (worker_type = ANY (ARRAY['employee'::text, 'contractor'::text, 'vendor'::text]));

-- Wave 2 scoped/lifecycle relations
ALTER TABLE public.service_request ADD CONSTRAINT service_request_business_unit_id_fkey FOREIGN KEY (business_unit_id) REFERENCES business_unit(id);
ALTER TABLE public.service_request ADD CONSTRAINT service_request_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES campaign(id);
ALTER TABLE public.service_request ADD CONSTRAINT service_request_contact_id_fkey FOREIGN KEY (contact_id) REFERENCES contact(id);
ALTER TABLE public.service_request ADD CONSTRAINT service_request_created_by_app_user_id_fkey FOREIGN KEY (created_by_app_user_id) REFERENCES app_user(id);
ALTER TABLE public.service_request ADD CONSTRAINT service_request_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES customer(id);
ALTER TABLE public.service_request ADD CONSTRAINT service_request_external_reference_id_fkey FOREIGN KEY (external_reference_id) REFERENCES external_reference(id);
ALTER TABLE public.service_request ADD CONSTRAINT service_request_idempotency_key_id_fkey FOREIGN KEY (idempotency_key_id) REFERENCES idempotency_key(id);
ALTER TABLE public.service_request ADD CONSTRAINT service_request_lifecycle_status_check CHECK (lifecycle_status = ANY (ARRAY['intake'::text, 'qualified'::text, 'disqualified'::text, 'converted'::text, 'cancelled'::text]));
ALTER TABLE public.service_request ADD CONSTRAINT service_request_marketing_source_id_fkey FOREIGN KEY (marketing_source_id) REFERENCES marketing_source(id);
ALTER TABLE public.service_request ADD CONSTRAINT service_request_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organization(id);
ALTER TABLE public.service_request ADD CONSTRAINT service_request_pkey PRIMARY KEY (id);
ALTER TABLE public.service_request ADD CONSTRAINT service_request_service_category_check CHECK (btrim(service_category) <> ''::text);
ALTER TABLE public.service_request ADD CONSTRAINT service_request_service_location_id_fkey FOREIGN KEY (service_location_id) REFERENCES service_location(id);
ALTER TABLE public.service_request ADD CONSTRAINT service_request_updated_by_app_user_id_fkey FOREIGN KEY (updated_by_app_user_id) REFERENCES app_user(id);
ALTER TABLE public.service_request ADD CONSTRAINT uq_service_request_scope UNIQUE (id, organization_id, business_unit_id);
ALTER TABLE public.opportunity ADD CONSTRAINT fk_opportunity_service_request_scope FOREIGN KEY (service_request_id, organization_id, business_unit_id) REFERENCES service_request(id, organization_id, business_unit_id) ON DELETE RESTRICT;
ALTER TABLE public.opportunity ADD CONSTRAINT opportunity_business_unit_id_fkey FOREIGN KEY (business_unit_id) REFERENCES business_unit(id);
ALTER TABLE public.opportunity ADD CONSTRAINT opportunity_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES campaign(id);
ALTER TABLE public.opportunity ADD CONSTRAINT opportunity_contact_id_fkey FOREIGN KEY (contact_id) REFERENCES contact(id);
ALTER TABLE public.opportunity ADD CONSTRAINT opportunity_created_by_app_user_id_fkey FOREIGN KEY (created_by_app_user_id) REFERENCES app_user(id);
ALTER TABLE public.opportunity ADD CONSTRAINT opportunity_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES customer(id);
ALTER TABLE public.opportunity ADD CONSTRAINT opportunity_external_reference_id_fkey FOREIGN KEY (external_reference_id) REFERENCES external_reference(id);
ALTER TABLE public.opportunity ADD CONSTRAINT opportunity_idempotency_key_id_fkey FOREIGN KEY (idempotency_key_id) REFERENCES idempotency_key(id);
ALTER TABLE public.opportunity ADD CONSTRAINT opportunity_marketing_source_id_fkey FOREIGN KEY (marketing_source_id) REFERENCES marketing_source(id);
ALTER TABLE public.opportunity ADD CONSTRAINT opportunity_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organization(id);
ALTER TABLE public.opportunity ADD CONSTRAINT opportunity_pkey PRIMARY KEY (id);
ALTER TABLE public.opportunity ADD CONSTRAINT opportunity_probability_percent_check CHECK (probability_percent IS NULL OR probability_percent >= 0::numeric AND probability_percent <= 100::numeric);
ALTER TABLE public.opportunity ADD CONSTRAINT opportunity_service_location_id_fkey FOREIGN KEY (service_location_id) REFERENCES service_location(id);
ALTER TABLE public.opportunity ADD CONSTRAINT opportunity_stage_check CHECK (stage = ANY (ARRAY['open'::text, 'qualified'::text, 'proposal'::text, 'won'::text, 'lost'::text, 'cancelled'::text]));
ALTER TABLE public.opportunity ADD CONSTRAINT opportunity_updated_by_app_user_id_fkey FOREIGN KEY (updated_by_app_user_id) REFERENCES app_user(id);
ALTER TABLE public.opportunity ADD CONSTRAINT uq_opportunity_scope UNIQUE (id, organization_id, business_unit_id);
ALTER TABLE public.opportunity ADD CONSTRAINT uq_opportunity_service_request UNIQUE (service_request_id);
ALTER TABLE public.estimate ADD CONSTRAINT estimate_business_unit_id_fkey FOREIGN KEY (business_unit_id) REFERENCES business_unit(id);
ALTER TABLE public.estimate ADD CONSTRAINT estimate_contact_id_fkey FOREIGN KEY (contact_id) REFERENCES contact(id);
ALTER TABLE public.estimate ADD CONSTRAINT estimate_created_by_app_user_id_fkey FOREIGN KEY (created_by_app_user_id) REFERENCES app_user(id);
ALTER TABLE public.estimate ADD CONSTRAINT estimate_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES customer(id);
ALTER TABLE public.estimate ADD CONSTRAINT estimate_lifecycle_status_check CHECK (lifecycle_status = ANY (ARRAY['draft'::text, 'prepared'::text, 'sent'::text, 'accepted'::text, 'superseded'::text, 'rejected'::text, 'expired'::text, 'cancelled'::text]));
ALTER TABLE public.estimate ADD CONSTRAINT estimate_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organization(id);
ALTER TABLE public.estimate ADD CONSTRAINT estimate_pkey PRIMARY KEY (id);
ALTER TABLE public.estimate ADD CONSTRAINT estimate_service_location_id_fkey FOREIGN KEY (service_location_id) REFERENCES service_location(id);
ALTER TABLE public.estimate ADD CONSTRAINT estimate_updated_by_app_user_id_fkey FOREIGN KEY (updated_by_app_user_id) REFERENCES app_user(id);
ALTER TABLE public.estimate ADD CONSTRAINT estimate_version_no_check CHECK (version_no >= 1);
ALTER TABLE public.estimate ADD CONSTRAINT fk_estimate_opportunity_scope FOREIGN KEY (opportunity_id, organization_id, business_unit_id) REFERENCES opportunity(id, organization_id, business_unit_id) ON DELETE RESTRICT;
ALTER TABLE public.estimate ADD CONSTRAINT uq_estimate_opportunity_version UNIQUE (opportunity_id, version_no);
ALTER TABLE public.estimate ADD CONSTRAINT uq_estimate_scope UNIQUE (id, organization_id, business_unit_id);
ALTER TABLE public.pricing_snapshot ADD CONSTRAINT fk_pricing_snapshot_estimate_scope FOREIGN KEY (estimate_id, organization_id, business_unit_id) REFERENCES estimate(id, organization_id, business_unit_id) ON DELETE RESTRICT;
ALTER TABLE public.pricing_snapshot ADD CONSTRAINT fk_pricing_snapshot_opportunity_scope FOREIGN KEY (opportunity_id, organization_id, business_unit_id) REFERENCES opportunity(id, organization_id, business_unit_id) ON DELETE RESTRICT;
ALTER TABLE public.pricing_snapshot ADD CONSTRAINT pricing_snapshot_business_unit_id_fkey FOREIGN KEY (business_unit_id) REFERENCES business_unit(id);
ALTER TABLE public.pricing_snapshot ADD CONSTRAINT pricing_snapshot_configuration_version_id_fkey FOREIGN KEY (configuration_version_id) REFERENCES configuration_version(id);
ALTER TABLE public.pricing_snapshot ADD CONSTRAINT pricing_snapshot_created_by_app_user_id_fkey FOREIGN KEY (created_by_app_user_id) REFERENCES app_user(id);
ALTER TABLE public.pricing_snapshot ADD CONSTRAINT pricing_snapshot_currency_code_check CHECK (currency_code ~ '^[A-Z]{3}$'::text);
ALTER TABLE public.pricing_snapshot ADD CONSTRAINT pricing_snapshot_discount_amount_check CHECK (discount_amount >= 0::numeric);
ALTER TABLE public.pricing_snapshot ADD CONSTRAINT pricing_snapshot_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organization(id);
ALTER TABLE public.pricing_snapshot ADD CONSTRAINT pricing_snapshot_pkey PRIMARY KEY (id);
ALTER TABLE public.pricing_snapshot ADD CONSTRAINT pricing_snapshot_subtotal_amount_check CHECK (subtotal_amount >= 0::numeric);
ALTER TABLE public.pricing_snapshot ADD CONSTRAINT pricing_snapshot_tax_amount_check CHECK (tax_amount >= 0::numeric);
ALTER TABLE public.pricing_snapshot ADD CONSTRAINT pricing_snapshot_tax_rate_check CHECK (tax_rate >= 0::numeric AND tax_rate <= 1::numeric);
ALTER TABLE public.pricing_snapshot ADD CONSTRAINT pricing_snapshot_total_amount_check CHECK (total_amount >= 0::numeric);
ALTER TABLE public.pricing_snapshot ADD CONSTRAINT uq_pricing_snapshot_scope UNIQUE (id, organization_id, business_unit_id);
ALTER TABLE public.quote ADD CONSTRAINT fk_quote_estimate_scope FOREIGN KEY (estimate_id, organization_id, business_unit_id) REFERENCES estimate(id, organization_id, business_unit_id) ON DELETE RESTRICT;
ALTER TABLE public.quote ADD CONSTRAINT fk_quote_opportunity_scope FOREIGN KEY (opportunity_id, organization_id, business_unit_id) REFERENCES opportunity(id, organization_id, business_unit_id) ON DELETE RESTRICT;
ALTER TABLE public.quote ADD CONSTRAINT quote_business_unit_id_fkey FOREIGN KEY (business_unit_id) REFERENCES business_unit(id);
ALTER TABLE public.quote ADD CONSTRAINT quote_contact_id_fkey FOREIGN KEY (contact_id) REFERENCES contact(id);
ALTER TABLE public.quote ADD CONSTRAINT quote_created_by_app_user_id_fkey FOREIGN KEY (created_by_app_user_id) REFERENCES app_user(id);
ALTER TABLE public.quote ADD CONSTRAINT quote_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES customer(id);
ALTER TABLE public.quote ADD CONSTRAINT quote_lifecycle_status_check CHECK (lifecycle_status = ANY (ARRAY['draft'::text, 'active'::text, 'accepted'::text, 'declined'::text, 'expired'::text, 'cancelled'::text]));
ALTER TABLE public.quote ADD CONSTRAINT quote_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organization(id);
ALTER TABLE public.quote ADD CONSTRAINT quote_pkey PRIMARY KEY (id);
ALTER TABLE public.quote ADD CONSTRAINT quote_service_location_id_fkey FOREIGN KEY (service_location_id) REFERENCES service_location(id);
ALTER TABLE public.quote ADD CONSTRAINT quote_updated_by_app_user_id_fkey FOREIGN KEY (updated_by_app_user_id) REFERENCES app_user(id);
ALTER TABLE public.quote ADD CONSTRAINT uq_quote_scope UNIQUE (id, organization_id, business_unit_id);
ALTER TABLE public.quote_version ADD CONSTRAINT fk_quote_version_estimate_scope FOREIGN KEY (estimate_id, organization_id, business_unit_id) REFERENCES estimate(id, organization_id, business_unit_id) ON DELETE RESTRICT;
ALTER TABLE public.quote_version ADD CONSTRAINT fk_quote_version_pricing_scope FOREIGN KEY (pricing_snapshot_id, organization_id, business_unit_id) REFERENCES pricing_snapshot(id, organization_id, business_unit_id) ON DELETE RESTRICT;
ALTER TABLE public.quote_version ADD CONSTRAINT fk_quote_version_quote_scope FOREIGN KEY (quote_id, organization_id, business_unit_id) REFERENCES quote(id, organization_id, business_unit_id) ON DELETE RESTRICT;
ALTER TABLE public.quote_version ADD CONSTRAINT quote_version_business_unit_id_fkey FOREIGN KEY (business_unit_id) REFERENCES business_unit(id);
ALTER TABLE public.quote_version ADD CONSTRAINT quote_version_created_by_app_user_id_fkey FOREIGN KEY (created_by_app_user_id) REFERENCES app_user(id);
ALTER TABLE public.quote_version ADD CONSTRAINT quote_version_lifecycle_status_check CHECK (lifecycle_status = ANY (ARRAY['draft'::text, 'sent'::text, 'accepted'::text, 'declined'::text, 'expired'::text, 'cancelled'::text]));
ALTER TABLE public.quote_version ADD CONSTRAINT quote_version_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organization(id);
ALTER TABLE public.quote_version ADD CONSTRAINT quote_version_pkey PRIMARY KEY (id);
ALTER TABLE public.quote_version ADD CONSTRAINT quote_version_updated_by_app_user_id_fkey FOREIGN KEY (updated_by_app_user_id) REFERENCES app_user(id);
ALTER TABLE public.quote_version ADD CONSTRAINT quote_version_version_no_check CHECK (version_no >= 1);
ALTER TABLE public.quote_version ADD CONSTRAINT uq_quote_version_number UNIQUE (quote_id, version_no);
ALTER TABLE public.quote_version ADD CONSTRAINT uq_quote_version_pricing_snapshot UNIQUE (pricing_snapshot_id);
ALTER TABLE public.quote_version ADD CONSTRAINT uq_quote_version_scope UNIQUE (id, organization_id, business_unit_id);
ALTER TABLE public.quote_response ADD CONSTRAINT fk_quote_response_quote_version_scope FOREIGN KEY (quote_version_id, organization_id, business_unit_id) REFERENCES quote_version(id, organization_id, business_unit_id) ON DELETE RESTRICT;
ALTER TABLE public.quote_response ADD CONSTRAINT quote_response_business_unit_id_fkey FOREIGN KEY (business_unit_id) REFERENCES business_unit(id);
ALTER TABLE public.quote_response ADD CONSTRAINT quote_response_created_by_app_user_id_fkey FOREIGN KEY (created_by_app_user_id) REFERENCES app_user(id);
ALTER TABLE public.quote_response ADD CONSTRAINT quote_response_idempotency_key_id_fkey FOREIGN KEY (idempotency_key_id) REFERENCES idempotency_key(id);
ALTER TABLE public.quote_response ADD CONSTRAINT quote_response_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organization(id);
ALTER TABLE public.quote_response ADD CONSTRAINT quote_response_pkey PRIMARY KEY (id);
ALTER TABLE public.quote_response ADD CONSTRAINT quote_response_response_type_check CHECK (response_type = ANY (ARRAY['viewed'::text, 'requested_changes'::text, 'accepted'::text, 'declined'::text, 'expired'::text]));
ALTER TABLE public.quote_response ADD CONSTRAINT uq_quote_response_scope UNIQUE (id, organization_id, business_unit_id);
ALTER TABLE public.conversion_record ADD CONSTRAINT conversion_record_business_unit_id_fkey FOREIGN KEY (business_unit_id) REFERENCES business_unit(id);
ALTER TABLE public.conversion_record ADD CONSTRAINT conversion_record_contact_id_fkey FOREIGN KEY (contact_id) REFERENCES contact(id);
ALTER TABLE public.conversion_record ADD CONSTRAINT conversion_record_created_by_app_user_id_fkey FOREIGN KEY (created_by_app_user_id) REFERENCES app_user(id);
ALTER TABLE public.conversion_record ADD CONSTRAINT conversion_record_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES customer(id);
ALTER TABLE public.conversion_record ADD CONSTRAINT conversion_record_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organization(id);
ALTER TABLE public.conversion_record ADD CONSTRAINT conversion_record_pkey PRIMARY KEY (id);
ALTER TABLE public.conversion_record ADD CONSTRAINT conversion_record_service_location_id_fkey FOREIGN KEY (service_location_id) REFERENCES service_location(id);
ALTER TABLE public.conversion_record ADD CONSTRAINT fk_conversion_estimate_scope FOREIGN KEY (estimate_id, organization_id, business_unit_id) REFERENCES estimate(id, organization_id, business_unit_id) ON DELETE RESTRICT;
ALTER TABLE public.conversion_record ADD CONSTRAINT fk_conversion_opportunity_scope FOREIGN KEY (opportunity_id, organization_id, business_unit_id) REFERENCES opportunity(id, organization_id, business_unit_id) ON DELETE RESTRICT;
ALTER TABLE public.conversion_record ADD CONSTRAINT fk_conversion_quote_response_scope FOREIGN KEY (quote_response_id, organization_id, business_unit_id) REFERENCES quote_response(id, organization_id, business_unit_id) ON DELETE RESTRICT;
ALTER TABLE public.conversion_record ADD CONSTRAINT fk_conversion_quote_scope FOREIGN KEY (quote_id, organization_id, business_unit_id) REFERENCES quote(id, organization_id, business_unit_id) ON DELETE RESTRICT;
ALTER TABLE public.conversion_record ADD CONSTRAINT fk_conversion_quote_version_scope FOREIGN KEY (quote_version_id, organization_id, business_unit_id) REFERENCES quote_version(id, organization_id, business_unit_id) ON DELETE RESTRICT;
ALTER TABLE public.conversion_record ADD CONSTRAINT fk_conversion_service_request_scope FOREIGN KEY (service_request_id, organization_id, business_unit_id) REFERENCES service_request(id, organization_id, business_unit_id) ON DELETE RESTRICT;
ALTER TABLE public.conversion_record ADD CONSTRAINT uq_conversion_quote_response UNIQUE (quote_response_id);
ALTER TABLE public.conversion_record ADD CONSTRAINT uq_conversion_quote_version UNIQUE (quote_version_id);
ALTER TABLE public.conversion_record ADD CONSTRAINT uq_conversion_scope UNIQUE (id, organization_id, business_unit_id);
ALTER TABLE public.job_handoff ADD CONSTRAINT fk_job_handoff_conversion_scope FOREIGN KEY (conversion_record_id, organization_id, business_unit_id) REFERENCES conversion_record(id, organization_id, business_unit_id) ON DELETE RESTRICT;
ALTER TABLE public.job_handoff ADD CONSTRAINT fk_job_handoff_pricing_scope FOREIGN KEY (pricing_snapshot_id, organization_id, business_unit_id) REFERENCES pricing_snapshot(id, organization_id, business_unit_id) ON DELETE RESTRICT;
ALTER TABLE public.job_handoff ADD CONSTRAINT fk_job_handoff_quote_version_scope FOREIGN KEY (quote_version_id, organization_id, business_unit_id) REFERENCES quote_version(id, organization_id, business_unit_id) ON DELETE RESTRICT;
ALTER TABLE public.job_handoff ADD CONSTRAINT job_handoff_business_unit_id_fkey FOREIGN KEY (business_unit_id) REFERENCES business_unit(id);
ALTER TABLE public.job_handoff ADD CONSTRAINT job_handoff_created_by_app_user_id_fkey FOREIGN KEY (created_by_app_user_id) REFERENCES app_user(id);
ALTER TABLE public.job_handoff ADD CONSTRAINT job_handoff_handoff_status_check CHECK (handoff_status = ANY (ARRAY['ready'::text, 'dispatched_to_wave3'::text, 'cancelled'::text]));
ALTER TABLE public.job_handoff ADD CONSTRAINT job_handoff_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organization(id);
ALTER TABLE public.job_handoff ADD CONSTRAINT job_handoff_pkey PRIMARY KEY (id);
ALTER TABLE public.job_handoff ADD CONSTRAINT uq_job_handoff_conversion UNIQUE (conversion_record_id);
ALTER TABLE public.job_handoff ADD CONSTRAINT uq_job_handoff_scope UNIQUE (id, organization_id, business_unit_id);

CREATE INDEX idx_audit_entity ON public.audit_event USING btree (entity_type, entity_id, occurred_at DESC);
CREATE INDEX idx_business_unit_org ON public.business_unit USING btree (organization_id);
CREATE INDEX idx_config_lookup ON public.configuration_version USING btree (organization_id, configuration_type, status);
CREATE INDEX idx_contact_customer ON public.contact USING btree (customer_id);
CREATE INDEX idx_conversion_record_core ON public.conversion_record USING btree (organization_id, business_unit_id, quote_version_id);
CREATE INDEX idx_customer_bu ON public.customer USING btree (business_unit_id);
CREATE INDEX idx_customer_org ON public.customer USING btree (organization_id);
CREATE INDEX idx_estimate_org_bu_status ON public.estimate USING btree (organization_id, business_unit_id, lifecycle_status);
CREATE INDEX idx_external_entity ON public.external_reference USING btree (entity_type, entity_id);
CREATE INDEX idx_job_handoff_core ON public.job_handoff USING btree (organization_id, business_unit_id, conversion_record_id);
CREATE INDEX idx_lineage_source ON public.migration_lineage USING btree (source_table, source_id);
CREATE INDEX idx_opportunity_org_bu_stage ON public.opportunity USING btree (organization_id, business_unit_id, stage);
CREATE INDEX idx_pricing_snapshot_configuration ON public.pricing_snapshot USING btree (configuration_version_id);
CREATE INDEX idx_pricing_snapshot_estimate ON public.pricing_snapshot USING btree (estimate_id);
CREATE INDEX idx_pricing_snapshot_org_bu ON public.pricing_snapshot USING btree (organization_id, business_unit_id);
CREATE INDEX idx_quote_org_bu_status ON public.quote USING btree (organization_id, business_unit_id, lifecycle_status);
CREATE INDEX idx_quote_response_version ON public.quote_response USING btree (quote_version_id, response_type);
CREATE UNIQUE INDEX uq_quote_response_single_final ON public.quote_response USING btree (quote_version_id) WHERE (response_type = ANY (ARRAY['accepted'::text, 'declined'::text, 'expired'::text]));
CREATE INDEX idx_quote_version_org_bu_status ON public.quote_version USING btree (organization_id, business_unit_id, lifecycle_status);
CREATE INDEX idx_location_customer ON public.service_location USING btree (customer_id);
CREATE INDEX idx_service_request_attribution ON public.service_request USING btree (marketing_source_id, campaign_id);
CREATE INDEX idx_service_request_org_bu_status ON public.service_request USING btree (organization_id, business_unit_id, lifecycle_status);
CREATE INDEX idx_membership_org ON public.user_membership USING btree (organization_id);
CREATE INDEX idx_membership_user ON public.user_membership USING btree (app_user_id);
CREATE INDEX idx_worker_org ON public.worker USING btree (organization_id);
